# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.

$activeBorderColor = rgb(c42b2b)
$inactiveBorderColor = rgb(1a1618)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
    border_size = 2
    gaps_in = 4
    gaps_out = 8
}

group {
    col.border_active = $activeBorderColor
}

animations {
    enabled = yes

    bezier = strike, 0.16, 0.90, 0.30, 1

    animation = windows, 1, 5, strike
    animation = windowsIn, 1, 5, strike
    animation = windowsOut, 1, 4, strike
    animation = windowsMove, 1, 5, strike

    animation = fade, 1, 4, strike
    animation = fadeIn, 1, 4, strike
    animation = fadeOut, 1, 3, strike

    animation = layers, 1, 4, strike
    animation = layersIn, 1, 4, strike
    animation = layersOut, 1, 3, strike

    animation = workspaces, 1, 5, strike
}

decoration {
    shadow {
        enabled = true
        range = 14
        render_power = 4
        offset = 0 2
    }
    active_opacity = 0.98
    inactive_opacity = 0.92
    fullscreen_opacity = 1.0
}

layerrule = blur on, match:namespace walker
layerrule = ignore_alpha 0, match:namespace walker
layerrule = blur on, match:namespace waybar
layerrule = blur on, match:namespace notifications
layerrule = ignore_alpha 0, match:namespace notifications
layerrule = blur on, match:namespace vicinae
layerrule = blur on, match:namespace swayosd
layerrule = ignore_alpha 0.1, match:namespace waybar
layerrule = ignore_alpha 0.1, match:namespace vicinae
