$color = rgba(14, 12, 12, 1)
$inner_color = rgba(14, 12, 12, 0.66)
$outer_color = rgba(196, 43, 43, 1)
$font_color = rgba(232, 228, 224, 1)
$placeholder_color = rgba(232, 228, 224, 0.7)
$check_color = rgba(196, 43, 43, 1)
